import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import {ThemeProvider} from "@/components/ThemeProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body className={"bg-zinc-200/50 text-zinc-800 dark:bg-zinc-900 dark:text-zinc-200 antialiased scroll-smooth"}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >

            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
