import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import {ThemeProvider} from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import AppSidebar from "@/components/AppSidebar";
import {SidebarProvider} from "@/components/ui/sidebar";
import {cookies} from "next/headers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: ReactNode;
}>) {
    const cookieStore = await cookies()
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body className={"bg-zinc-200/50 text-zinc-800 dark:bg-zinc-900 dark:text-zinc-200 antialiased scroll-smooth"}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider defaultOpen={defaultOpen}>
                <AppSidebar/>
                <div className={"w-full"}>
                    <Navbar/>
                    <div className={"px-4"}>
                        {children}
                    </div>
                </div>
            </SidebarProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
